### ISSUE TITLE
Download is not finishing

### ISSUE THREAD

**Issue by sq5rix** [render-examples/fastai-v3#16]
Hi!
Thank you for excellent piece of code. I managed to run everything perfectly with local model file . However, when i run with download, it breaks:
https://pastebin.com/cD5rKTAU
I use Google drive, the link is:
https://drive.google.com/uc?export=download&id=1YRfTm2mDjzz7NjPxRPQN5k5KkXV6Nt_m
Greetings,
Tom

**Comment by anurag** [comment]
This issue seems to be specific to your model: feel free to post in https://forums.fast.ai/t/deployment-platform-render/33953/174 if you're still running into it.
