### ISSUE TITLE
torch-1.0.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by tbass134** [render-examples/fastai-v3#4]
I'm building the sample app and running into this error when trying to install the requirements on a mac
`torch-1.0.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.`

What is the proper install url for osx?

Thanks

**Comment by anurag** [comment]
I'd look at https://pytorch.org/get-started/locally/ and replace the value in `requirements.txt`.
